### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by chycken** [DeadSwimek/cs2-vip#14]
16:18:17 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VIP.VIP.Give_Values(CCSPlayerController controller) in C:\Users\ondra\Desktop\CS2 Pluginy\VIPGUNS Public\VIP.cs:line 512
   at VIP.VIP.OnClientSpawn(EventPlayerSpawn event, GameEventInfo info) in C:\Users\ondra\Desktop\CS2 Pluginy\VIPGUNS Public\Hooks.cs:line 266
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

I dont know what is it, but server crashed. Latest cssharp and plugin version

**Comment by DeadSwimek** [comment]
Hello, this is not crash error, this is only warning, server cannot give give value functions.
