### ISSUE TITLE
Error when adding VIP

### ISSUE THREAD

**Issue by y3request** [DeadSwimek/cs2-vip#16]
I updated plugin today and I get this error when trying to add a VIP. I updated cssharp, your plugin, and others today.

15:06:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Value to add was out of range. (Parameter 'value')
   at System.DateTime.ThrowAddOutOfRange()
   at System.DateTime.AddDays(Double value)
   at VIP.VIP.CommandAddVIP(CCSPlayerController player, CommandInfo info) in C:\Users\ondra\Desktop\CS2 Pluginy\VIPGUNS Public\Commands.cs:line 258
   at CounterStrikeSharp.API.Core.BasePlugin.<>c__DisplayClass41_0.<AddCommand>b__0(Int32 i, IntPtr ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 259
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by DeadSwimek** [comment]
Can u show me, how u adding VIP?

**Comment by y3request** [comment]
css_addvip in server console

**Comment by s1neX1987** [comment]
> Can u show me, how u adding VIP?

same error i have

**Comment by DeadSwimek** [comment]
css_addvip is not for Console, is only client use.

**Comment by NoSetViolin** [comment]
why im not admin,and how can i set me to admin pls
