### ISSUE TITLE
Bhop

### ISSUE THREAD

**Issue by chycken** [DeadSwimek/cs2-vip#26]
Hello, bhop is now working for vips.
Config is ok, i checked it.
Another bugs: -server sometimes crashes
-getting this on console:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.CBasePlayerPawn.get_WeaponServices() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 5183
   at VIP.VIP.CheckIsHaveWeapon(String weapon_name, CCSPlayerController pc) in C:\Users\ondra\Desktop\CS2 Pluginy\VIPGUNS Public\VIP.cs:line 470
   at VIP.VIP.OnRoundStart(EventRoundStart event, GameEventInfo info) in C:\Users\ondra\Desktop\CS2 Pluginy\VIPGUNS Public\Hooks.cs:line 172
   at InvokeStub_GameEventHandler1.Invoke(Object, Object, IntPtr)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>cDisplayClass3_0.<.ctor>b0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 82

**Comment by chycken** [comment]
@DeadSwimek  any up?
